groups:
  - name: system-alerts
    rules:
      - alert: HighCPUUsage
        expr: (100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage"
          description: "CPU usage above 80% for 1 minute."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Memory Usage"
          description: "Memory usage above 85%."

      - alert: NodeExporterDown
        expr: up{job="node_exporter"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter Down"
          description: "Node Exporter is not responding"

      - alert: AppDemoDown
        expr: up{job="app-demo"} == 0
        for: 15s
        labels:
          severity: warning
        annotations:
          description: "app-demo service is not responding"
          summary: "App Down Alert"
